fix

diff --git a/.github/workflows/infra-deploy.yml b/.github/workflows/infra-deploy.yml
--- a/.github/workflows/infra-deploy.yml
+++ b/.github/workflows/infra-deploy.yml
@@ -31,7 +31,11 @@ jobs:
       id: tf_output
       working-directory: infra/terraform
       run: |
-        SERVER_IP=$(terraform output -raw odoo_server_ip)
-        echo "odoo_server_ip=$SERVER_IP" >> $GITHUB_ENV
+        SERVER_IP=$(terraform output -raw odoo_server_ip 2>dev/null || echo "")
+        if [-z "$SERVER_IP"]; then
+          echo "SERVER_IP not found"
+          exit 1
+        fi
+        printf "odoo_server_ip=%s\n" "$SERVER_IP" >> $GITHUB_ENV
      
 
